name = "your-daily-progress"
main = "dist/server/server.js"
compatibility_date = "2025-06-13"
compatibility_flags = ["nodejs_compat"]

[vars]
CF_ACCOUNT_ID = "7ae8d26215d22e65db04d1ce0febe9e7"
CF_D1_DATABASE_ID = "0bdf02e5-7bca-4130-a5ad-bb7e6f4e93e9"
VITE_FIREBASE_API_KEY = "AIzaSyCTZjGb-WSk5-z4w4GakZ64VRl7cx_QD9c"
VITE_FIREBASE_AUTH_DOMAIN = "daily-progress-ad412.firebaseapp.com"
VITE_FIREBASE_PROJECT_ID = "daily-progress-ad412"
VITE_FIREBASE_STORAGE_BUCKET = "daily-progress-ad412.firebasestorage.app"
VITE_FIREBASE_MESSAGING_SENDER_ID = "487660252596"
VITE_FIREBASE_APP_ID = "1:487660252596:web:9487e7db79b07388ecd6e1"

[[d1_databases]]
binding = "DB"
database_name = "creatorconnect"
database_id = "0bdf02e5-7bca-4130-a5ad-bb7e6f4e93e9"

[[durable_objects.bindings]]
name = "SIGNAL_ROOM"
class_name = "SignalingRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SignalingRoom"]

[assets]
directory = "dist/client"
binding = "ASSETS"
